name: "Build Artefacts"

on: 
    workflow_dispatch:
    workflow_call:

jobs:
    build_linux:
        name: Build Linux
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with: 
                python-version: '3.11.1'
            
            - name: Install Requirements
              run: |
                python -m pip install -U pip
                curl -sSL https://install.python-poetry.org | python3 -
                poetry install --with dev

            - name: Build
              run: |
                poetry build
                poetry run python ./utils/build.py
            
            - name: Upload Artefacts
              uses: actions/upload-artifact@v3
              with: 
                path: |
                    dist/*

    build_window:
        name: Build Window
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with: 
                python-version: '3.11.1'
            
            - name: Install Requirements
              run: |
                python -m pip install -U pip
                curl -sSL https://install.python-poetry.org | python3 -
                C:\Users\runneradmin\AppData\Roaming\Python\Scripts\poetry install --with dev
            
            - name: Install libmpv
              run: |
                New-Item -ItemType Directory libmpv
                Set-Location libmpv
                Invoke-WebRequest -UserAgent "Wget" -Uri "https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-v3-20230924-git-140d018.7z/download" -OutFile libmpv.7z
                7z x libmpv.7z
                Move-Item libmpv-2.dll ..\mpv-2.dll
                Set-Location ..
                Remove-Item libmpv -Recurse -Force


            - name: Build
              run: |
                C:\Users\runneradmin\AppData\Roaming\Python\Scripts\poetry run python ./utils/build.py
            
            - name: Upload Artefacts
              uses: actions/upload-artifact@v3
              with: 
                path: |
                    dist/LISTEN.tui.exe
                    dist/LISTEN.tui-portable.exe
        

                



